### ISSUE TITLE
Is julia 1.10 required?

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/MultiBroadcastFusion.jl#29]
https://github.com/CliMA/MultiBroadcastFusion.jl/blob/0d6c83cc3e0a1673560ec75b53b9e3f80954c7ba/Project.toml#L14

This requirement pins ClimaCore to 0.13.3 for julia 1.9, is it possible to lower the requirement to 1.9, or are features from 1.10 needed?

**Comment by charleskawczynski** [comment]
Yeah, we can use lower versions of julia
